In [3]:
import pandas as pd

In [4]:
data = ([['Sahitya',78],['Jack',97],['Kush',88]])
data

[['Sahitya', 78], ['Jack', 97], ['Kush', 88]]

In [5]:
pd.DataFrame(data,columns=['Name','Makrs'])

      Name  Makrs
0  Sahitya     78
1     Jack     97
2     Kush     88

In [6]:
data = { "a":[4,5,6],"b":[56,34,88]}
pd.DataFrame(data)

   a   b
0  4  56
1  5  34
2  6  88

In [22]:
arr = ([[1,2,3],[5,6,7]])

In [23]:
import pandas as pd

pd.DataFrame(arr, columns=["S0", "S1", "S2"])

   S0  S1  S2
0   1   2   3
1   5   6   7

In [3]:


pd.read_excel("data.xls")

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [11]:
pd.read_csv("Data.csv")

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [4]:


df = pd.read_json('Data.json')

df = pd.json_normalize(df['airports'])
display(df)

,code,name,city,country,lat,lon
0,ATL,Hartsfield-Jackson Atlanta International,Atlanta,US,33.6407,-84.4277
1,PEK,Beijing Capital International,Beijing,CN,40.0801,116.5846
2,DXB,Dubai International,Dubai,AE,25.2528,55.3644
3,LAX,Los Angeles International,Los Angeles,US,33.9425,-118.4081
4,HND,Tokyo Haneda,Tokyo,JP,35.5494,139.7798
5,ORD,O'Hare International,Chicago,US,41.9742,-87.9073
6,LHR,London Heathrow,London,GB,51.4700,-0.4543
7,PVG,Shanghai Pudong International,Shanghai,CN,31.1443,121.8083
8,CDG,Paris Charles de Gaulle,Paris,FR,49.0097,2.5479
9,DFW,Dallas/Fort Worth International,Dallas,US,32.8998,-97.0403
10,CAN,Guangzhou Baiyun International,Guangzhou,CN,23.3924,113.2988
11,AMS,Amsterdam Schiphol,Amsterdam,NL,52.3105,4.7683
12,FRA,Frankfurt Airport,Frankfurt,DE,50.0379,8.5622
13,IST,Istanbul Airport,Istanbul,TR,41.2753,28.7519
14,SIN,Singapore Changi,Singapore,SG,1.3644,103.9915
15,ICN,Incheon International,Seoul,KR,37.4602,126.4407
16,DEN,Denver International,Denver,US,39.8561,-104.6737
17,BKK,Suvarnabhumi Airport,Bangkok,TH,13.6900,100.7501
18,JFK,John F. Kennedy International,New York,US,40.6413,-73.7781
19,HKG,Hong Kong International,Hong Kong,HK,22.3080,113.9185
20,KUL,Kuala Lumpur International,Kuala Lumpur,MY,2.7456,101.7099
21,MAD,Adolfo Suárez Madrid–Barajas,Madrid,ES,40.4983,-3.5676
22,SFO,San Francisco International,San Francisco,US,37.6213,-122.3790
23,MIA,Miami International,Miami,US,25.7959,-80.2870
24,SYD,Sydney Kingsford Smith,Sydney,AU,-33.9399,151.1753
25,MUC,Munich Airport,Munich,DE,48.3537,11.7750
26,BCN,Barcelona–El Prat,Barcelona,ES,41.2974,2.0833
27,YYZ,Toronto Pearson International,Toronto,CA,43.6777,-79.6248
28,MEX,Mexico City International,Mexico City,MX,19.4361,-99.0719
29,NRT,Narita International,Tokyo,JP,35.7720,140.3929

In [12]:
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

)

In [13]:
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [14]:
df.head() #Start 5 Row

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [15]:
df.tail() # Last in 5 Row

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [17]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [19]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [21]:
df.shape

(149, 5)